import Link from "next/link";
import { Check, Edit3, Pause, RotateCcw, X } from "lucide-react";
import { CallerFactoryRunner } from "@/components/CallerFactoryRunner";
import { StudioNav } from "@/components/StudioNav";
import { acceptAllCallerCandidatesAction, acceptCallerCandidateAction, rejectCallerCandidateAction, restoreCallerCandidateAction, setCallerBatchStatusAction } from "@/lib/actions/caller-factory-actions";
import { requireAdmin } from "@/lib/auth";
import { moduleEnabled } from "@/lib/modules";
import { prisma } from "@/lib/prisma";
import { generatedCallerDraftSchema } from "@/lib/schemas";

const record = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};

export default async function CallerFactoryBatchPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<{ edited?: string }> }) {
  await requireAdmin();
  if (!(await moduleEnabled("CALLER_FACTORY"))) return <main className="shell"><StudioNav /><p>Caller Factory is disabled.</p></main>;
  const { batchId } = await params;
  const query = await searchParams;
  const batch = await prisma.callerGenerationBatch.findUniqueOrThrow({ where: { id: batchId }, include: { show: { select: { title: true } }, candidates: { orderBy: { createdAt: "asc" } } } });
  const criteria = record(batch.criteria);
  const pendingCount = batch.candidates.filter((candidate) => candidate.status === "PENDING").length;
  return <main className="shell"><StudioNav />
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow"><Link href="/callers/factory" className="hover:text-cyan-100">Caller Factory</Link> / {batch.status}</p><h1 className="title mt-1">{batch.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{batch.seed}</p></div><div className="flex gap-2">{batch.status === "RUNNING" && <form action={setCallerBatchStatusAction.bind(null, batch.id, "PAUSED")}><button className="button-secondary"><Pause className="h-4 w-4" /> Pause</button></form>}{["PAUSED", "FAILED"].includes(batch.status) && <form action={setCallerBatchStatusAction.bind(null, batch.id, "RUNNING")}><button className="button-secondary"><RotateCcw className="h-4 w-4" /> Make resumable</button></form>}{!["COMPLETED", "CANCELLED"].includes(batch.status) && <form action={setCallerBatchStatusAction.bind(null, batch.id, "CANCELLED")}><button className="button-danger"><X className="h-4 w-4" /> Cancel</button></form>}</div></div>
    <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-800 px-3 py-1 text-slate-300">Tone: {String(criteria.tone ?? "varied")}</span><span className="rounded-full bg-slate-800 px-3 py-1 text-slate-300">Mix: {String(criteria.mix ?? "balanced")}</span><span className="rounded-full bg-slate-800 px-3 py-1 text-slate-300">Intensity: {String(criteria.intensity ?? "medium")}</span>{batch.show && <span className="rounded-full bg-cyan-300/10 px-3 py-1 text-cyan-200">For {batch.show.title}</span>}</div>
    {query.edited === "1" && <p className="mt-4 rounded-xl border border-emerald-300/30 bg-emerald-300/5 p-3 text-sm text-emerald-100">Candidate changes saved.</p>}
    {batch.error && <p className="mt-4 rounded-xl border border-rose-300/30 bg-rose-300/5 p-3 text-sm text-rose-100">{batch.error}</p>}
    <div className="mt-5"><CallerFactoryRunner batchId={batch.id} status={batch.status} generatedCount={batch.generatedCount} targetCount={batch.targetCount} /></div>
    <div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Candidate inbox</p><h2 className="mt-1 text-xl font-bold text-white">Review before the library</h2><p className="mt-1 text-sm text-slate-400">Accept creates an editable caller draft. Reject keeps the candidate here without adding it anywhere else.</p></div>{pendingCount > 0 && <form action={acceptAllCallerCandidatesAction.bind(null, batch.id)}><button className="button-secondary"><Check className="h-4 w-4" /> Accept all {pendingCount} pending</button></form>}</div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2">{batch.candidates.map((candidate, index) => { const draft = generatedCallerDraftSchema.parse(candidate.draft); return <article key={candidate.id} className={`panel panel-pad ${candidate.status === "REJECTED" ? "opacity-55" : ""}`}>
      <div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Candidate {index + 1}</p><h3 className="mt-1 text-lg font-bold text-white">{draft.firstName} {draft.surnameInitial}</h3><p className="mt-1 text-xs text-slate-400">{draft.age} · {draft.location} · {draft.occupation}</p></div><span className={`status ${candidate.status === "ACCEPTED" ? "bg-emerald-300/10 text-emerald-200" : candidate.status === "REJECTED" ? "bg-slate-700 text-slate-300" : "bg-violet-300/10 text-violet-200"}`}>{candidate.status}</span></div>
      <h4 className="mt-4 font-bold text-slate-100">{draft.issueHeadline}</h4><p className="mt-2 text-sm leading-6 text-slate-300">{draft.openingSummary}</p>
      <div className="mt-3 flex flex-wrap gap-1">{draft.topicTags.map((tag) => <span key={tag} className="rounded-full bg-slate-800 px-2 py-1 text-[11px] text-cyan-100">{tag}</span>)}</div>
      {draft.autoVisuals?.status === "READY" && <div className="mt-4"><div className="flex items-center justify-between gap-2"><p className="label">Automatic visuals</p><span className="text-[10px] text-emerald-200">{draft.autoVisuals.items.length} credited images ready</span></div><div className="mt-2 grid grid-cols-3 gap-2">{draft.autoVisuals.items.map((image) => <div key={image.id} className="overflow-hidden rounded-lg border border-slate-700 bg-slate-950"><img src={image.previewUrl} alt={image.alt} className="aspect-video h-full w-full object-cover" title={`${image.creator} · ${image.provider}`} /></div>)}</div></div>}
      {draft.autoVisuals?.status === "FAILED" && <p className="mt-4 rounded-lg border border-amber-300/20 bg-amber-300/5 p-2 text-xs text-amber-100">Visual preparation skipped: {draft.autoVisuals.error}. The caller can still be accepted and will use its portrait.</p>}
      <details className="mt-4 rounded-xl border border-slate-700 bg-slate-950/35 p-3"><summary className="cursor-pointer text-sm font-bold text-slate-300">Private caller shape</summary><dl className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="label">Wants</dt><dd className="mt-1 text-slate-300">{draft.desiredOutcome}</dd></div><div><dt className="label">Tension</dt><dd className="mt-1 text-slate-300">{draft.internalTension}</dd></div><div><dt className="label">Speech</dt><dd className="mt-1 text-slate-300">{draft.speechStyle}</dd></div><div><dt className="label">Voice</dt><dd className="mt-1 text-slate-300">{draft.voicePresentation} · {draft.voiceId}</dd></div></dl></details>
      <div className="mt-4 flex flex-wrap gap-2">{candidate.status === "PENDING" && <><Link className="button-secondary" href={`/callers/factory/candidates/${candidate.id}`}><Edit3 className="h-4 w-4" /> Edit</Link><form action={acceptCallerCandidateAction.bind(null, batch.id, candidate.id)}><button className="button-primary"><Check className="h-4 w-4" /> Accept to library</button></form><form action={rejectCallerCandidateAction.bind(null, batch.id, candidate.id)}><button className="button-secondary"><X className="h-4 w-4" /> Reject</button></form></>}{candidate.status === "ACCEPTED" && candidate.acceptedCallerId && <Link className="button-primary" href={`/callers/${candidate.acceptedCallerId}`}>Open caller draft</Link>}{candidate.status === "REJECTED" && <form action={restoreCallerCandidateAction.bind(null, batch.id, candidate.id)}><button className="button-secondary"><RotateCcw className="h-4 w-4" /> Restore</button></form>}</div>
    </article>; })}{batch.candidates.length === 0 && <div className="panel panel-pad text-sm text-slate-400 lg:col-span-2">This batch is intentionally empty. Press Build caller pack when you are ready to start generation.</div>}</div>
  </main>;
}
