"use client";

import { useState } from "react";
import { AudioLines, Images, Music2, Square } from "lucide-react";
import { BackgroundMusicPanel } from "@/components/BackgroundMusicPanel";
import { builtInCues, musicTracks, type BuiltInCueId, type DeckState } from "@/lib/studio-audio";
import type { StudioState } from "@/lib/studio-state";

export function StudioOnAirTools({ visuals, activeVisualUrl, onVisual, sounds, onSound, onStopSound, onCue, onStopEffects, cueState, cueVolume, onCueVolume, musicState, musicVolume, musicLoop, onMusic, onStopMusic, onMusicVolume, onMusicLoop }: {
  visuals: { id: string; label: string; url: string; manualHotkey?: string | null }[]; activeVisualUrl?: string;
  onVisual: (id: string | null) => void; sounds: StudioState["soundEffects"];
  onSound: (effect: StudioState["soundEffects"][number]) => void; onStopSound: (id: string) => void;
  onCue: (id: BuiltInCueId) => void; onStopEffects: () => void; cueState: DeckState; cueVolume: number; onCueVolume: (value: number) => void;
  musicState: DeckState; musicVolume: number; musicLoop: boolean; onMusic: (track: typeof musicTracks[number]) => void; onStopMusic: () => void; onMusicVolume: (value: number) => void; onMusicLoop: (value: boolean) => void;
}) {
  const [pane, setPane] = useState<"visuals" | "sounds" | "music">("visuals");
  const playing = musicState.status === "playing" || musicState.status === "loading";
  const currentTrack = musicTracks.find((track) => track.id === musicState.id);
  const cueButton = (cue: typeof builtInCues[number]) => <button type="button" key={cue.id} aria-label={`Play ${cue.title}${cue.key ? ` (${cue.key})` : ""}`} onClick={() => onCue(cue.id)} className={`rounded-lg border p-3 text-left text-xs font-bold transition-colors ${cueState.id === cue.id && cueState.status === "playing" ? "border-cyan-300/50 bg-cyan-950/40 text-cyan-100" : "border-slate-700/50 bg-slate-800 text-slate-100 hover:bg-slate-700"}`}>{cue.title}{cue.key && <kbd className="ml-2 text-[10px] text-slate-400">{cue.key}</kbd>}</button>;
  return <section className="panel panel-pad" aria-label="On-air tools">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">On-air tools</p><div className="flex rounded-lg bg-slate-950 p-1 text-xs font-bold" aria-label="Tool categories">{[{ id: "visuals" as const, label: "Visuals", Icon: Images }, { id: "sounds" as const, label: "Sounds", Icon: AudioLines }, { id: "music" as const, label: "Music", Icon: Music2 }].map(({ id, label, Icon }) => <button key={id} type="button" aria-pressed={pane === id} onClick={() => setPane(id)} className={`flex items-center gap-1.5 rounded-md px-2 py-2 ${pane === id ? "bg-cyan-400 text-slate-950" : "text-slate-300 hover:text-white"}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div></div>
    {playing && <div className="mt-3 flex items-center gap-2 rounded-lg border border-cyan-300/20 bg-cyan-950/20 px-3 py-2 text-xs" role="status"><Music2 className="h-3.5 w-3.5 shrink-0 text-cyan-200" /><span className="min-w-0 flex-1 truncate text-cyan-100">{musicState.status === "loading" ? "Loading" : "Playing"}: {currentTrack?.title}</span><button type="button" onClick={onStopMusic} aria-label="Stop background music" className="flex shrink-0 items-center gap-1 rounded px-2 py-1 font-bold text-cyan-200"><Square className="h-3 w-3" />Stop</button></div>}
    {pane === "visuals" && <><div className="mt-3 flex items-center justify-between gap-2"><p className="text-xs text-slate-400">Tap an image to put it on air.</p><button type="button" onClick={() => onVisual(null)} className="text-xs font-bold text-cyan-200">Clear visual</button></div><div className="mt-3 grid max-h-80 grid-cols-2 gap-2 overflow-y-auto pr-1">{visuals.length ? visuals.map((asset, index) => {
      const selected = activeVisualUrl === asset.url;
      return <button type="button" key={asset.id} onClick={() => onVisual(asset.id)} aria-label={`Show visual ${asset.manualHotkey ?? index + 1}: ${asset.label}`} aria-pressed={selected} className={`relative aspect-video overflow-hidden rounded-lg border bg-slate-950 text-left hover:border-cyan-400 ${selected ? "border-cyan-300 ring-1 ring-cyan-300" : "border-slate-700"}`}><img className="h-full w-full object-cover" src={asset.url} alt="" /><span className="absolute bottom-1.5 left-1.5 rounded bg-slate-950/85 px-1.5 py-0.5 text-[10px] font-bold text-cyan-200">{asset.manualHotkey ?? index + 1}</span>{selected && <span className="absolute right-1.5 top-1.5 rounded bg-cyan-300 px-1.5 py-0.5 text-[9px] font-bold uppercase text-slate-950">On air</span>}</button>;
    }) : <p className="col-span-2 py-4 text-sm text-slate-400">No prepared caller visuals yet.</p>}</div></>}
    {pane === "sounds" && <div className="mt-3 space-y-3"><p className="text-xs leading-5 text-slate-400">Real applause, a drum sting and proper phone cues. Short, level-matched samples; keyboard shortcuts still work.</p><div className="grid grid-cols-2 gap-2">{builtInCues.filter((cue) => cue.key).map(cueButton)}</div><div className="rounded-xl bg-slate-950/60 p-3"><div className="flex items-center justify-between gap-3"><label htmlFor="cue-volume" className="text-xs text-slate-300">Effects volume · {Math.round(cueVolume * 100)}%</label><button type="button" onClick={onStopEffects} className="flex items-center gap-1.5 text-xs font-bold text-cyan-200"><Square className="h-3 w-3" />Stop effects</button></div><input id="cue-volume" className="mt-2 w-full accent-cyan-300" aria-label="Sound effects volume" type="range" min="0" max="1" step="0.01" value={cueVolume} onChange={(event) => onCueVolume(Number(event.target.value))} /></div><details><summary className="cursor-pointer text-xs text-slate-400">Preview automatic phone cues</summary><p className="mt-2 text-[11px] leading-5 text-slate-500">These also run automatically when a caller arrives, connects or the host ends the call. Previewing only plays the sound.</p><div className="mt-2 grid grid-cols-2 gap-2">{builtInCues.filter((cue) => !cue.key).map(cueButton)}</div></details>{sounds.length > 0 && <div className="grid grid-cols-2 gap-2">{sounds.map((effect) => <div key={effect.id} className="rounded-lg border border-slate-700 p-3"><button type="button" onClick={() => onSound(effect)} className="w-full text-left text-xs font-bold text-slate-100">{effect.label}{effect.hotkey ? ` [${effect.hotkey}]` : ""}</button><button type="button" onClick={() => onStopSound(effect.id)} className="mt-2 text-[10px] font-bold text-cyan-200">Stop</button></div>)}</div>}<p className="text-[11px] text-slate-500">Custom URL cues can be added in Show options. <a href="/audio/CREDITS.txt" target="_blank" rel="noreferrer" className="underline">Sound sources (CC0)</a></p>{cueState.error && <p role="alert" className="text-xs text-rose-200">{cueState.error}</p>}</div>}
    <div hidden={pane !== "music"}><BackgroundMusicPanel state={musicState} volume={musicVolume} loop={musicLoop} onPlay={onMusic} onStop={onStopMusic} onVolume={onMusicVolume} onLoop={onMusicLoop} /></div>
  </section>;
}
