import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { addCallerToShowAction, addSoundEffectAction, deleteShowAction, deleteSoundEffectAction, moveQueueItemAction, updateShowAction } from "@/lib/actions/show-actions";
import { ShowPreflight } from "@/components/ShowPreflight";
import { StudioNav } from "@/components/StudioNav";

export default async function ShowDetailPage({ params }: { params: Promise<{ showId: string }> }) {
  await requireAdmin();
  const { showId } = await params;
  const [show, approvedCallers] = await Promise.all([
    prisma.show.findUniqueOrThrow({ where: { id: showId }, include: { queueItems: { include: { caller: { include: { assets: true } } }, orderBy: { position: "asc" } }, soundEffects: { orderBy: { createdAt: "asc" } } } }),
    prisma.caller.findMany({ where: { status: "APPROVED" }, orderBy: { firstName: "asc" } }),
  ]);
  const broadcastUrl = `/broadcast/${show.id}?token=${show.broadcastToken}&mode=full`;
  return <main className="shell"><StudioNav /><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Show / {show.status}</p><h1 className="title mt-1">{show.title}</h1><p className="mt-2 text-sm text-slate-400">Broadcast state: {show.broadcastState.replaceAll("_", " ")}</p></div><div className="flex flex-wrap gap-2"><Link href={`/studio?show=${show.id}`} className="button-primary">Open Host Studio</Link><Link href={broadcastUrl} target="_blank" className="button-secondary">Open broadcast display</Link></div></div>
  <div className="mt-5 flex flex-wrap items-end gap-2 rounded-xl border border-slate-800 bg-slate-900/50 p-3"><form action={updateShowAction.bind(null, show.id)} className="flex flex-wrap items-end gap-2"><label><span className="label">Programme title</span><input className="field !mt-0 !w-72" name="title" defaultValue={show.title} required /></label><button className="button-secondary">Save title</button></form>{show.status !== "LIVE" && <form action={deleteShowAction.bind(null, show.id)}><button className="button-danger">Delete show</button></form>}</div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="panel panel-pad"><div className="flex items-center justify-between"><div><p className="eyebrow">Live queue</p><h2 className="mt-1 text-lg font-bold text-white">Running order</h2></div><span className="text-xs text-slate-400">Use arrows for this Phase 1 queue; drag ordering follows in production hardening.</span></div><div className="mt-4 space-y-2">{show.queueItems.map((item, index) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-950/60 p-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-800 text-xs font-bold">{item.position}</span><div className="min-w-0 flex-1"><p className="font-semibold text-white">{item.caller.firstName} {item.caller.surnameInitial}</p><p className="truncate text-xs text-slate-400">{item.caller.issueHeadline}</p></div><span className="status bg-slate-800 text-slate-300">{item.status}</span><div className="flex gap-1"><form action={moveQueueItemAction.bind(null, show.id, item.id, "up")}><button className="button-secondary !min-h-8 !px-2" disabled={index === 0} aria-label="Move up">↑</button></form><form action={moveQueueItemAction.bind(null, show.id, item.id, "down")}><button className="button-secondary !min-h-8 !px-2" disabled={index === show.queueItems.length - 1} aria-label="Move down">↓</button></form></div></div>)}{show.queueItems.length === 0 && <p className="rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-400">The running order is empty.</p>}</div></section>
  <div className="space-y-6"><ShowPreflight show={show} /><form action={addCallerToShowAction.bind(null, show.id)} className="panel panel-pad h-fit"><p className="eyebrow">Queue caller</p><h2 className="mt-1 text-lg font-bold text-white">Add approved caller</h2><label className="mt-5 block"><span className="label">Caller</span><select className="field" name="callerId" defaultValue="" required><option value="" disabled>Select a caller</option>{approvedCallers.map((caller) => <option key={caller.id} value={caller.id}>{caller.firstName} {caller.surnameInitial} — {caller.issueHeadline}</option>)}</select></label><button className="button-primary mt-4 w-full" disabled={approvedCallers.length === 0}>Add to end of queue</button>{approvedCallers.length === 0 && <p className="mt-3 text-xs leading-5 text-slate-400">Only callers manually marked Approved can be added.</p>}</form><section className="panel panel-pad"><p className="eyebrow">Soundboard</p><h2 className="mt-1 text-lg font-bold text-white">Show audio cues</h2><div className="mt-3 space-y-2">{show.soundEffects.map((effect) => <div key={effect.id} className="flex items-center justify-between gap-2 rounded-lg bg-slate-950 p-2 text-sm"><span className="min-w-0 truncate text-slate-200">{effect.label}{effect.loop ? " · loop" : ""}</span><form action={deleteSoundEffectAction.bind(null, show.id, effect.id)}><button className="text-xs font-bold text-red-300">Remove</button></form></div>)}</div><form action={addSoundEffectAction.bind(null, show.id)} className="mt-4 grid gap-3"><label><span className="label">Cue label</span><input className="field" name="label" placeholder="Incoming call" required /></label><label><span className="label">Audio URL</span><input className="field" name="url" type="url" placeholder="https://…/sting.mp3" required /></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Volume</span><input className="field" name="volume" type="number" min="0" max="1" step="0.1" defaultValue="0.8" /></label><label><span className="label">Hotkey label</span><input className="field" name="hotkey" placeholder="F1" /></label></div><label className="flex items-center gap-2 text-sm text-slate-300"><input name="loop" type="checkbox" /> Loop until stopped</label><button className="button-secondary">Add sound cue</button></form></section><p className="text-xs leading-5 text-slate-400">OBS link uses an unguessable show token. The public route serializes only caller name, location, issue, portrait and actively selected visual.</p></div></div></main>;
}
